# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  build: ./cobis
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    - "5045:5045"
    - "5046:5046"
